### ISSUE TITLE
Nice work! Small mistake in paper re: sgpt

### ISSUE THREAD

**Issue by Muennighoff** [guilhermemr04/scaling-zero-shot-retrieval#6]
Great work! I had been waiting for someone to just scale up a Cross-Encoder to be large enough to set a new SoTA on BEIR. 

"_2 SGPT results are not completely zero-shot as the prompt was chosen based on the effectiveness in 6 datasets of the BEIR benchmark._" 
This only applies to the SGPT Cross-Encoder (CE), but I think you compare with the dense SGPT model (Bi-Encoder). The Bi-Encoder did not use any prompting. It was fine-tuned on MSMARCO, thus BEIR results are zero-shot.

Also I think in the scaling graph for SGPT the first three dots are the Cross-Encoder & the last one is the Bi-Encoder. It doesn't make a lot of sense to compare them like this, thus the jump for the last dot. I guess it's partly my fault, as I've only provided full BEIR results for the 5.8B model in the SGPT paper. I will look into adding results for the smaller models to the paper.

**Comment by rodrigonogueira4** [comment]
Hi Niklas,
You are right in both points, sorry about that!
We will update the arxiv version as soon as possible with the corrections.

**Comment by Muennighoff** [comment]
Sure, I think you can leave the last one as is for now. 
I will try to train smaller models this week and provide you with the numbers so you can update the graph if you wish.

**Comment by rodrigonogueira4** [comment]
Awesome, looking forward to it!

**Comment by guilhermemr04** [comment]
Hi Niklas, we've already updated the paper and the mistake is fixed.

**Comment by Muennighoff** [comment]
Nice, I also just finished the eval of all the smaller models. Feel free to add them to the graph if you wish.

The average nDCG@10 scores (w/o msmarco) are (the links lead to the full BEIR scores):
[2.7B](https://huggingface.co/Muennighoff/SGPT-2.7B-weightedmean-msmarco-specb-bitfit/blob/main/eval/beir.json):  `0.453`
[1.3B](https://huggingface.co/Muennighoff/SGPT-1.3B-weightedmean-msmarco-specb-bitfit/blob/main/eval/beir.json): `0.433`
[125M](https://huggingface.co/Muennighoff/SGPT-125M-weightedmean-msmarco-specb-bitfit/blob/main/eval/beir.json): `0.357`
